export const ingredients: string[] = [
    "apple",
    "apricot",
    "artichoke",
    "arugula",
    "asparagus",
    "avocado",
    "bacon",
    "baking powder",
    "baking soda",
    "banana",
    "basil",
    "bay leaf",
    "beans",
    "beef",
    "beet",
    "bell pepper",
    "black pepper",
    "blueberry",
    "bread",
    "brown sugar",
    "butter",
    "cabbage",
    "cake flour",
    "canola oil",
    "carrot",
    "cashews",
    "cauliflower",
    "celery",
    "cheddar cheese",
    "cheese",
    "cherry",
    "chicken breast",
    "chickpeas",
    "chives",
    "cilantro",
    "cinnamon",
    "cloves",
    "cocoa powder",
    "coconut",
    "coconut milk",
    "cod",
    "corn",
    "cornmeal",
    "cottage cheese",
    "cream",
    "cream cheese",
    "cucumber",
    "cumin",
    "currants",
    "dates",
    "dill",
    "egg",
    "eggplant",
    "evaporated milk",
    "farro",
    "feta cheese",
    "fig",
    "flaxseed",
    "flour",
    "garlic",
    "ginger",
    "goat cheese",
    "grape",
    "grapefruit",
    "green beans",
    "green onion",
    "ground beef",
    "ground pork",
    "guava",
    "honey",
    "iceberg lettuce",
    "jalapeno",
    "jam",
    "kale",
    "ketchup",
    "kidney beans",
    "kiwi",
    "lamb",
    "leek",
    "lemon",
    "lettuce",
    "lime",
    "macadamia nuts",
    "mango",
    "maple syrup",
    "marjoram",
    "mayonnaise",
    "milk",
    "mint",
    "mozzarella",
    "mushroom",
    "mustard",
    "nectarine",
    "nutmeg",
    "oats",
    "olive oil",
    "onion",
    "orange",
    "oregano",
    "papaya",
    "parmesan cheese",
    "parsley",
    "parsnip",
    "pasta",
    "pea",
    "peach",
    "peanut butter",
    "peanuts",
    "pear",
    "peas",
    "pecan",
    "pepper",
    "pine nuts",
    "pineapple",
    "pistachio",
    "plum",
    "pomegranate",
    "popcorn",
    "pork",
    "potato",
    "pumpkin",
    "quinoa",
    "radish",
    "raisin",
    "raspberry",
    "red onion",
    "rice",
    "ricotta",
    "rosemary",
    "rutabaga",
    "rye bread",
    "sage",
    "salmon",
    "salt",
    "scallion",
    "sesame oil",
    "shrimp",
    "smoked salmon",
    "snap peas",
    "sour cream",
    "soy sauce",
    "spinach",
    "spirulina",
    "squash",
    "strawberry",
    "sugar",
    "sunflower seed",
    "sweet potato",
    "swiss cheese",
    "tangerine",
    "thyme",
    "tofu",
    "tomato",
    "tuna",
    "turkey",
    "vanilla",
    "vanilla extract",
    "walnut",
    "water",
    "watercress",
    "wheat germ",
    "whipped cream",
    "white chocolate",
    "white onion",
    "whole milk",
    "yeast",
    "yogurt",
    "zucchini"
];
